### ISSUE TITLE
Build fails: chkinp.F90:722:132: Error: Line truncated at (1) [-Werror=line-truncation]

### ISSUE THREAD

**Issue by yurivict** [abinit/abinit#1]
chkinp.F90:722:132: Error: Line truncated at (1) [-Werror=line-truncation]
chkinp.F90:722:131: Error: Syntax error in argument list at (1)
chkinp.F90:725:132: Error: Line truncated at (1) [-Werror=line-truncation]
chkinp.F90:725:131: Error: Syntax error in argument list at (1)
dfpt_dyfro.F90:160:132: Error: Line truncated at (1) [-Werror=line-truncation]
dfpt_dyfro.F90:160:128: Error: Unterminated character constant beginning at (1)
dfpt_rhotov.F90:151:132: Error: Line truncated at (1) [-Werror=line-truncation]
dfpt_rhotov.F90:151:132: Error: Syntax error in argument list at (1)

Version 8.2.2

**Comment by gmatteo** [comment]
Please add `-ffree-line-length-none` to your FCFLAGS when configuring.
We don't enforce the 132 characters limit in Abinit
