### ISSUE TITLE
Doesn't install the headers and libraries

### ISSUE THREAD

**Issue by yurivict** [abinit/abinit#11]
The ```abinit.pc``` file says
```
Libs: -L${libdir} -lab7_parser
Cflags: -I${includedir}/abinit
```
but no headers and libraries are installed.

OS: FreeBSD
Version: 8.8.2

**Comment by piti-diablotin** [comment]
Hi

I think you need to enbale the binding of abinit when configuring abinit.
But this binding is not maintained anymore. 
As you can notice, this `ab7_parser` whereas we are at Abinit8 !!
So this is not safe to use.

Cheers

Jordan
