### ISSUE TITLE
Error from prtkbff2

### ISSUE THREAD

**Issue by WFKala** [abinit/abinit#17]
Error raised when the options is activated:
`prtkbff2   1`

The error is 
`forrtl: severe (61): format/variable-type mismatch, unit -5, file Internal Formatted Write`

The error comes from `src/67_common/m_iowf.F90`

>                  write(msg,'(a10,i5,a,a10,e12.4,a,3(a10,2e12.4,a))') &
>                         'projector ', iproj,ch10, &
>                         'vkbsign   ', vkbsign(iproj,iat), ch10, &
>                         'vkb       ', vkb(1,iproj,iat),  vkb(npwk_disk,:,iat), ch10, &
>                         'vkbd      ', vkbd(1,iproj,iat), vkbd(npwk_disk,:,iat), ''

To my understanding it is used to output vkb(1,*,*) and vkb(npwk_disk,*,*). 

The format string does not look like correct.  Only two terms vkb and vkbd are used, but the format string is `3(a10,2e12.4,a)`. Also, `vkb(npwk_disk,:,iat)` seems to be `vkb(npwk_disk,iproj,iat)` as it is not an arrray in the format string.

**Comment by jmbeuken** [comment]
Can you send me 

- your input file 
- abinit version
- compiler version 

thanks

**Comment by WFKala** [comment]
Hi jmbeuken,
     Sorry I don't have access to the old input files now.  A normal SCF with JTH PAW pseudo potential and `prtkbff2` option should work.

ABINIT version: 8.10.1 and 8.10.2
Compiler version: Intel 2019 and 2019 update 1
