### ISSUE TITLE
Installs a wrong .pc file

### ISSUE THREAD

**Issue by yurivict** [abinit/abinit#18]
It installs the .pc file that contains ```-lab7_parser``` and ```-I/usr/local/include/abinit```, and it doesn't install ```libab7_parser.so``` library or corresponding headers.

Is the .pc file installed by mistake?

**Comment by jmbeuken** [comment]
the config.pc.in is outdated :  we need to update it...

> prefix=@prefix@
> exec_prefix=@exec_prefix@
> bindir=@bindir@
> includedir=@includedir@
> libdir=@libdir@
> 
> Name: Abinit
> Description: Atomic-scale simulation software
> Version: @PACKAGE_VERSION@
> URL: https://www.abinit.org/
> Requires: libatlas, netcdf
> Libs: -L${libdir} -lab7_parser
> Cflags: -I${includedir}/abinit
