### ISSUE TITLE
The calculation of Reflectivity

### ISSUE THREAD

**Issue by houzf** [abinit/abinit#31]
In the "src/44_abitools/m_optic_tools.F90", the calculations of "Reflectivity(w) from vacuum, at normal incidence" used the same equation for the "Re(refractive index(w)) aka n'". Pls  check it. 
----------------------------------------------------------------------------------
741    write(fout1, '(a)' )' # Energy(eV)         Re(refractive index(w)) aka n'
 742    do iw=2,nmesh
 743      ene=(iw-1)*de
 744      ene=ene*ha2ev
 745      write(fout1, '(2es16.6)' ) ene,sqrt(half*(abs(eps(iw)) + dble(eps(iw)) ))
 746    end do
 747    write(fout1,*)
 748    write(fout1,*)
 749    write(fout1, '(a)' )' # Energy(eV)         Reflectivity(w) from vacuum, at normal incidence'
 750    do iw=2,nmesh
 751      ene=(iw-1)*de
 752      ene=ene*ha2ev
 753      write(fout1, '(2es16.6)' ) ene, sqrt(half*(abs(eps(iw)) + dble(eps(iw)) ))
 754    end do
-----------------------------------------------------------------------------------------------------

**Comment by gonzex** [comment]
Thanks for the comment. Indeed, the reflectivity computation was screwed. This has been fixed in the development version of ABINIT. Wait for ABINITv9.2 to be released in two or three months. Well, if you cannot wait, write me at xavier.gonze@uclouvain.be .
