### ISSUE TITLE
Compile error with Ubuntu 20.04 standard libraries

### ISSUE THREAD

**Issue by askhl** [abinit/abinit#39]
I download abinit 9.2.1 on Ubuntu 20.04 with gcc/gfortran 9.3.

Then I run configure.  It says I need libxc, netcdf, and netcdf-fortran.

I install the -dev packages for each: `libxc-dev`, `libnetcdf-dev`, and `libnetcdff-dev`.

Then I run `./configure --prefix=$HOME/install/abinit-9.2.1 --with-libxc --with-netcdf --with-netcdf-fortran`.

The configure output tells me things are okay so I run `make` , but I get:

```
make[5]: *** No rule to make target 'm_optim_dumper.F90', needed by 'm_optim_dumper.o'.  Stop.
```

For context, here's part of the configure log:

```
 ==============================================================================
 === Final remarks                                                          ===
 ==============================================================================


Core build parameters
---------------------

  * C compiler       : gnu version 9.3
  * Fortran compiler : gnu version 9.3
  * architecture     : unknown unknown (64 bits)
  * debugging        : basic
  * optimizations    : standard

  * OpenMP enabled   : no (collapse: ignored)
  * MPI    enabled   : no (flavor: none)
  * MPI    in-place  : no
  * MPI-IO enabled   : no
  * GPU    enabled   : no (flavor: none)

  * LibXML2 enabled  : no
  * LibPSML enabled  : no
  * XMLF90  enabled  : no
  * HDF5 enabled     : yes (MPI support: no)
  * NetCDF enabled   : yes (MPI support: unknown)
  * NetCDF-F enabled : yes (MPI support: unknown)

  * FFT flavor       : goedecker (libs: auto-detected)
  * LINALG flavor    : netlib+openblas (libs: auto-detected)

  * Build workflow   : monolith

0 deprecated options have been used:.

Configuration complete.
You may now type "make" to build Abinit.
(or "make -j<n>", where <n> is the number of available processors)
```

Full output of the configure command:

[[configure.log](https://github.com/abinit/abinit/files/5512609/configure.log)](url)

I note that two lines are written to stderr during configure as well:

```
realpath: '': No such file or directory
/usr/bin/env: 'python': No such file or directory
```

(I have python3 but no ordinary python.)

I take it that if `make` fails after okay'ing the configuration, it could be an issue with the build system.

**Comment by askhl** [comment]
A similar procedure compiles correctly on debian stable (10.6) with gcc/gfortran 8.3.  That computer has a `python` command so the stderr output does not mention the env python line.

**Comment by gmatteo** [comment]
> I take it that if make fails after okay'ing the configuration, it could be an issue with the build system.

The build system uses python to generate automatically `m_optim_dumper.F90` so  the python interpreter is considered a hard dependency.

The script used in Abinit assume the presence of a *python* executable whose location is found via /usr/bin/env.
If the distribution installs python3 without a symbolic link named python, one has to create it manually with e.g.

```
cd /usr/bin
ln -s python3 python
```

See also [this post in the forum](https://forum.abinit.org/viewtopic.php?f=3&t=4482#p13271)

The next version of the build system will abort at the beginning of the configuration step if python is not found.
The error message will explain how to fix the problem.

**Comment by askhl** [comment]
Thanks for the quick response @gmatteo.  Indeed it solves the problem.  Please feel free to close the issue then.  (Although I think it would be nice to allow a `python3` binary or `./configure --python=my_own_python` to avoid hacking the machine.)

**Comment by gmatteo** [comment]
>  I think it would be nice to allow a python3 binary or ./configure --python=my_own_python to avoid hacking the machine.)

I considered this option but it requires patching all the python scripts we have to replace `python` with `python3`.

I think that the `/usr/bin/env python`shebang is the most portable syntax for running scripts as it also supports python installations based on virtual envs, conda envs etc.
It seems that ubuntu provides.a [python-is-python3](https://packages.ubuntu.com/focal/python-is-python3) package to address this problem. 

Alternatively, one can create a symbolic link in the current working directory and then add the cwd to PYTHONPATH.

**Comment by mbanck** [comment]
`python` is gone from most distributions' development branch by now, and will be gone from the stable releases in a few months, it's certainly not portable anymore
