### ISSUE TITLE
Build and Execute issues with Fujitsu compiler 

### ISSUE THREAD

**Issue by t-karatsu** [abinit/abinit#43]
I am trying to install abinit using the Fujitsu compiler.
Two issues have occurred and have been addressed with the attached patch.

1. An error occurs because there are INTENT(OUT) variables definition for which no value has been set. Therefore, I changed the variable type as follows.
```
e.g.
diff -uprN src/43_wvl_wrappers/m_abi2big.F90 src/43_wvl_wrappers/m_abi2big.F90
--- src/43_wvl_wrappers/m_abi2big.F90	2019-01-17 20:49:35.000000000 +0900
+++ src/43_wvl_wrappers/m_abi2big.F90	2019-05-21 15:05:23.000000000 +0900
@@ -1333,10 +1333,10 @@ subroutine wvl_setngfft(me_wvl, mgfft, n
 
 !Arguments ------------------------------------
 !scalars
- integer, intent(out) :: mgfft, nfft
+ integer, intent(inout) :: mgfft, nfft
  integer, intent(in)  :: n1i, n2i, n3i,n3d, nproc_wvl, me_wvl
 !arrays
- integer, intent(out) :: ngfft(18)
+ integer, intent(inout) :: ngfft(18)
 
 !Local variables-------------------------------
 !scalars
```
2. When the abinit binary is executed after the building it and the parameter file is read, the following rewind process causes an error. Here, since the file is rewinded immediately after opening it in the new write mode, it was judged to be unnecessary processing in our environment and commented out.
```
diff -uprN src/98_main/abinit.F90 src/98_main/abinit.F90
--- src/98_main/abinit.F90	2019-01-17 20:49:35.000000000 +0900
+++ src/98_main/abinit.F90	2019-08-07 08:29:17.000000000 +0900
@@ -261,7 +261,7 @@ program abinit
    open(unit=ab_out,file=filnam(2),form='formatted',status='new', action="write", iomsg=message, iostat=ios)
 #endif
    ABI_CHECK(ios == 0, message)
-   rewind (unit=ab_out)
+!   rewind (unit=ab_out)
    codename='ABINIT'//repeat(' ',18)
    call herald(codename,abinit_version,ab_out)
    call herald(codename,abinit_version,std_out)
```

We recognize that these modifications are local and not generic. I'm not sure if these issues occur in other environments or compilers, but is it possible to fix them more generically and appropriately?

**Comment by gonzex** [comment]
Thank you very much ! Your patches have been ported to v9.3.4. The release, in v9.4.x, should happen soon.

**Comment by t-karatsu** [comment]
Thanks for confirming this!
