### ISSUE TITLE
some problems with compling the abinit

### ISSUE THREAD

**Issue by zc994646659** [abinit/abinit#48]
I installed NetCDF and NetCDF FORTRAN through RPM package and compilation, but they could not recognize them，how to solver the problem.
![微信图片_20210824161236](https://user-images.githubusercontent.com/76720982/130581499-77e6d9b7-bd05-47b1-bedb-f76356574143.png)

**Comment by AstralStorm** [comment]
The detection in abinit configure is completely broken. (See how their configure variables all specify paths?)
My recommendation is to use pkg-config. For example, this is for openmpi, scalapack, magma, atlas build:
```
export LINALG_CFLAGS="$(pkg-config --cflags ompi) $(pkg-config --cflags scalapack-openmpi) $(pkg-config --cflags magma) $(pkg-config --cflags blas-atlas) $(pkg-config --cflags lapack-atlas)"
export LINALG_LDFLAGS="$(pkg-config --libs ompi) $(pkg-config --libs scalapack-openmpi) $(pkg-config --libs magma) $(pkg-config --libs blas-atlas) $(pkg-config --libs lapack-atlas)"
```

I got very far in the build on Ubuntu 20.04 with abinit 9.6.1, but the thing fails to find some internal fortran modules, such as defs_basis. I'll check if Ubuntu has some extra patches.
