### ISSUE TITLE
abinit install error

### ISSUE THREAD

**Issue by zhonghua-lee** [abinit/abinit#5]
hello to all
I meet some difficulty when I install Abinit-6.2.3.
I download Abinit-6.2.3 from the official website, and I install with the commands as follows:

mkdir build
cd build
../configure
make

everything goes well before the ‘make’ command, but when I execute 'make', there are some error :

Error: Different shape for array assignment at (1) on dimension 1 (3 and 2)
Makefile:976: recipe for target 'odamix.o' failed
make[5]: *** [odamix.o] Error 1
make[5]: *** 正在等待未完成的任务....
make[5]: Leaving directory '/home/customer/software/abinit-6.2.3/build/src/67_common'
Makefile:816: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/customer/software/abinit-6.2.3/build/src'
Makefile:1061: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/customer/software/abinit-6.2.3/build'
Makefile:989: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/customer/software/abinit-6.2.3/build'
Makefile:1605: recipe for target 'multi' failed
make[1]: *** [multi] Error 2
make[1]: Leaving directory '/home/customer/software/abinit-6.2.3/build'
Makefile:1602: recipe for target 'mj4' failed
make: *** [mj4] Error 2

I  want some help. What should I do to solve the problem？

**Comment by ShihanWang** [comment]
I have the same issue.My operating system is Ubuntu16.04. I have not solve it! Need help....

**Comment by ShihanWang** [comment]
I solved the problem by changing the system with  Centos 7. Everything is OK.

**Comment by gmatteo** [comment]
Note that Abinit-6.2.3 is very old. Have your tried the last version https://www.abinit.org/package/8.6.1
