### ISSUE TITLE
Is  it possible to calculate the shg-density?

### ISSUE THREAD

**Issue by qingtianya-wyt** [abinit/abinit#50]
Dear abinit  team
I am using the abinit to calculate the nonlinear optical coefficients. I found shg-density could be used to analyse the origin of SHG. I want to know if there is a way to calculate it or show it out by some post-processing tools  based on the existing calculated data.

**Comment by jmbeuken** [comment]
Hi,

For this kind of question, it would be advantageous to ask it on the forum: https://discourse.abinit.org/

Cheers

**Comment by jmbeuken** [comment]
see https://discourse.abinit.org/t/how-to-calculate-phonon-at-wavevector-q-1-3-0-0-of-hcp-structure/3103
