### ISSUE TITLE
[9.6.2] Huge memory consumption makes any optic calculation impossible

### ISSUE THREAD

**Issue by Youjin1985** [abinit/abinit#51]
Dear developers,
I am doing optic calculation (like in tutorial on optical properties: https://docs.abinit.org/tutorial/optic/) on PNO system with only 6 atoms in primitive unit cell.
I can only do it up to ngkpt  12 12 12, which is nowhere near enough precision, according to tutorial.
Any higher value (like 16 16 16) crashes job on datasets 4-6 with out of memory (on node with 192 Gb RAM!!)
This makes utterly impossible to do any production calculations. 
Please optimize memory usage!

**Comment by jmbeuken** [comment]
Hi

Could you post your problem on the ABINIT forum: there is more hearing than on GitHUB?

https://discourse.abinit.org

Best,
