### ISSUE TITLE
Extract data from _DOS file

### ISSUE THREAD

**Issue by code-whale** [abinit/abinit#59]
Dear Abinit Team,

I'm a novice in DFT computing. When I learned the Spin tutorial of abinit, I encountered some problems. I want to get the data from the _DOS file through abipy or other python methods in order to customize the drawing, but I don't know what to do.

After I checked the ````tspin_1o_DS1_DOS```` file, I found that it contains the data I need for drawing, but I don't know how to extract them. I want to find functions like ````get_dataframe```` to extract data, but I haven't found them. I hope you can tell me how to use the abipy or other python methods to extract data. (It seems that my computer cannot install xmtrace at present, and I want my pictures to have the same style, so I want to be able to process it in Python.)

PS: ````tspin_1o_DS1_DOS````  file seems to have only one column, in which all data are separated by spaces, so I cannot use python subscripts to retrieve.

In addition, it seems that the abint forum is not open for registration at present, and the registration requires an invitation code, so I'm sorry to have to ask questions here, thank you for your help.

I attach the relevant pictures and documents below.

Best regards,
Jinyu Zhang

<img width="793" alt="image" src="https://user-images.githubusercontent.com/61874432/209963276-3f244343-cea4-4c2a-9231-449a5d01a46f.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/61874432/209963327-7a8dfd16-44d5-4e00-9f8d-33674e8ed996.png">

[tspin_1o_DS1_DOS.zip](https://github.com/abinit/abinit/files/10319817/tspin_1o_DS1_DOS.zip)

**Comment by jmbeuken** [comment]
migrated to discourse
