### ISSUE TITLE
Abinit old version

### ISSUE THREAD

**Issue by zhonghua-lee** [abinit/abinit#6]
hello, I want to use abinit-6.8.1，but I can not find it. It seems like it is been erased from the abinit website, could you tell me how to get it. thank you very much!

**Comment by gmatteo** [comment]
We recently migrated our website to https and not all previous links are working as expected.
We are woking on it

**Comment by jmbeuken** [comment]
https://www.abinit.org/sites/default/files/packages/abinit-6.8.1.tar.gz
or
https://www.abinit.org/sites/default/files/packages/abinit-6.8.2.tar.gz
