### ISSUE TITLE
Abinit installation problem

### ISSUE THREAD

**Issue by lolloso00** [abinit/abinit#62]
Hi, I'm trying to install abinit on my MacBook air M2, I'm following the procedure indicated on [https://docs.abinit.org/INSTALL_MacOS/](url) with home-brew. First of all when I run 
`brew install abinit`
I obtain the following error:
`Error: abinit: Failed to download resource "wannier90"`
`curl: (7) Failed to connect to forge.abinit.org port 80 after 53 ms: Connection refused`
So I tried to install abinit without wannier90 by running
`brew install abinit --without-wannier90`
and I also get the following error
`m_gwls_GenerateEpsilon.F90:182:35:

  182 | complex(dpc), intent(out) :: alpha(nseeds,nseeds,kmax)
      |                                   1
Error: Variable 'nseeds' cannot appear in the expression at (1)
m_gwls_GenerateEpsilon.F90:183:35:

  183 | complex(dpc), intent(out) :: beta (nseeds,nseeds,kmax)
      |                                   1
Error: Variable 'nseeds' cannot appear in the expression at (1)
make[3]: *** [m_gwls_GenerateEpsilon.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
`
How can I solve the problem?

**Comment by AlADonkov** [comment]
Hello, 
i had the same issue (opensuse, tumbleweed, gcc13.1.1), seems to be gcc related. 
After installing gcc10, and compiling all the prerequisites with it, this error did not arise, and abinit 9.8.4 did compile.

**Comment by brainandforce** [comment]
There was a response here about how abinit 9.8.4 does not support gcc 13, but the latest version (9.10.1 as of writing) does compile correctly.

**Comment by jmbeuken** [comment]
Hi, 
> Error: abinit: Failed to download resource "wannier90"
fixed
