### ISSUE TITLE
error in calculations with spin polarization, abinit with gpu support

### ISSUE THREAD

**Issue by wamuriel** [abinit/abinit#65]
Dear Abinit developers

I am a new user of the software and I am performing some calculations to get familiar with it, I compile the with gpu support, but when I perform calculations with spin polarization , I get the following error: 

../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.  
                                          .
                                          .
                                          .

../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
 cgwf: converged with tan2th=      1.3797E-16
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
 cgwf: converged with tan2th=      3.4102E-16
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
 cgwf: converged with tan2th=      3.6838E-16
../../../src/46_manage_cuda/gpu_compute_nl_hamiltonian.cu(788) : getLastCudaError() CUDA error : kernel_compute_nl_hamiltonian_64 : (9) invalid configuration argument.
 cgwf: converged with tan2th=      2.4732E-16

################### INPUT FILE ############################
# Control of the SCF cycle
# ========================
ecut          26  # Irrealist. Just to reduce the computation time in order to perform some benchmark
pawecutdg     33  # Minimal value not converge to run with ecut
nstep         60
toldfe        2.e-8
chksymtnons 0

# Electronic configuration
# ========================
#nband         640
occopt        7
tsmear        0.001
nsppol 2
nspinor 1
nspden 2
spinat
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 1.0
0.0 0.0 -1.0
0.0 0.0 1.0
0.0 0.0 1.0

### KPOINTS GRIDS
kptopt 0
#nkpt          1
#ngkpt 13 13 1
#shiftk    0.0    0.0    0.0
#nshiftk 1

##############################################
optcell 2
ionmov 2
ecutsm 0.005
dilatmx 1.05
chkdilatmx 0
tolmxf 2.0d-5
################

# Definition of the unit cell
# ===========================
chkprim  0
natom         150
ntypat        3
typat
1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1
1 1 2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2 2 2
2 2 2 3 3 3
znucl 5 7 6
xred
    0.0002311267    0.0002486825    0.5000000000
    0.0001463688    0.2001893331    0.5000000000
    0.9997280878    0.4000416995    0.5000000000
    0.9997363385    0.6000220637    0.5000000000
    0.0000674030    0.8001395689    0.5000000000
    0.1999644003    0.9997980743    0.5000000000
    0.2001957810    0.2000946171    0.5000000000
    0.1993512131    0.3999729302    0.5000000000
    0.1994675536    0.6002587890    0.5000000000
    0.1998585493    0.7999001650    0.5000000000
    0.3999619029    0.9996299861    0.5000000000
    0.3998065961    0.1988628940    0.5000000000
    0.4012939094    0.3986013012    0.5000000000
    0.3995016640    0.5997621997    0.5000000000
    0.3999732258    0.7999613702    0.5000000000
    0.6000667871    0.9998959272    0.5000000000
    0.6001241976    0.1995244760    0.5000000000
    0.6000027745    0.3993058925    0.5000000000
    0.6017994544    0.6027358618    0.5000000000
    0.6001312083    0.8002000908    0.5000000000
    0.8003245533    0.0003966170    0.5000000000
    0.8000408940    0.1999831286    0.5000000000
    0.7998835198    0.3999499863    0.5000000000
    0.7998493822    0.6000749269    0.5000000000
    0.8005378055    0.8006145707    0.5000000000
    0.0668730534    0.1335421817    0.5000000000
    0.0663853694    0.3333645294    0.5000000000
    0.0663024123    0.5333992131    0.5000000000
    0.0664797621    0.7333449934    0.5000000000
    0.0667743200    0.9334405517    0.5000000000
    0.2666058368    0.1329204229    0.5000000000
    0.2670824429    0.3337688293    0.5000000000
    0.2655515712    0.5338432623    0.5000000000
    0.2665161348    0.7333261145    0.5000000000
    0.2665773233    0.9330461251    0.5000000000
    0.4666666667    0.1327116184    0.5000000000
    0.4666666667    0.3310877048    0.5000000000
    0.4666666667    0.7333875755    0.5000000000
    0.4666666667    0.9331535815    0.5000000000
    0.6667560101    0.1331354685    0.5000000000
    0.6667274965    0.3329812527    0.5000000000
    0.6662508904    0.5333530531    0.5000000000
    0.6677817622    0.7349583578    0.5000000000
    0.6668171985    0.9334766464    0.5000000000
    0.8668535712    0.1335318980    0.5000000000
    0.8665590133    0.3333328984    0.5000000000
    0.8664602799    0.5333357950    0.5000000000
    0.8669479639    0.7336458266    0.5000000000
    0.8670309210    0.9337634674    0.5000000000
    0.1334498135    0.0667331331    0.5000000000
    0.1334839511    0.2668922114    0.5000000000
    0.1327955279    0.4667434319    0.5000000000
    0.1330087800    0.6667387304    0.5000000000
    0.1332924393    0.8666089013    0.5000000000
    0.3332091357    0.0660669450    0.5000000000
    0.3333305588    0.2659697847    0.5000000000
    0.3315338789    0.4676030741    0.5000000000
    0.3332021250    0.6667355491    0.5000000000
    0.3332665463    0.8664958068    0.5000000000
    0.5333714304    0.0663347498    0.5000000000
    0.5335267372    0.2657229645    0.5000000000
    0.5320394239    0.4639740584    0.5000000000
    0.5338316693    0.6669272023    0.5000000000
    0.5333601075    0.8666548111    0.5000000000
    0.7334747841    0.0667082824    0.5000000000
    0.7333689330    0.2665003407    0.5000000000
    0.7331375524    0.4665655027    0.5000000000
    0.7339821203    0.6672883838    0.5000000000
    0.7338657797    0.8674579020    0.5000000000
    0.9335969948    0.0669523918    0.5000000000
    0.9332659303    0.2667388325    0.5000000000
    0.9331022065    0.4666842225    0.5000000000
    0.9331869644    0.6667096309    0.5000000000
    0.9336052456    0.8669802784    0.5000000000
    0.0667981406    0.0001143445    0.5000000000
    0.0668437274    0.2001935805    0.5000000000
    0.0663181401    0.4000236404    0.5000000000
    0.0663814111    0.6000562768    0.5000000000
    0.0666226231    0.8000244664    0.5000000000
    0.2665225917    0.9995820008    0.5000000000
    0.2665759112    0.1995384146    0.5000000000
    0.2658641815    0.4001326594    0.5000000000
    0.2661141043    0.6004756301    0.5000000000
    0.2665520401    0.7999123975    0.5000000000
    0.4666666667    0.9997072627    0.5000000000
    0.4666666667    0.1991809402    0.5000000000
    0.4666666667    0.3969125542    0.5000000000
    0.4666666667    0.5996351949    0.5000000000
    0.4666666667    0.7999750603    0.5000000000
    0.6667812933    0.0000270240    0.5000000000
    0.6668107416    0.1997260758    0.5000000000
    0.6667574221    0.3996291700    0.5000000000
    0.6674691518    0.6009351446    0.5000000000
    0.6672192290    0.8010281924    0.5000000000
    0.8669519222    0.0003415323    0.5000000000
    0.8667107103    0.2000685099    0.5000000000
    0.8665351927    0.3999828705    0.5000000000
    0.8664896059    0.6000165198    0.5000000000
    0.8670151932    0.8003721670    0.5000000000
    0.1334951362    0.1334609377    0.5000000000
    0.1329261091    0.3332975551    0.5000000000
    0.1329400373    0.5334649172    0.5000000000
    0.1331168967    0.7333483807    0.5000000000
    0.1333118574    0.9332404714    0.5000000000
    0.3330889173    0.1325137835    0.5000000000
    0.3336377966    0.3328562710    0.5000000000
    0.3320801390    0.5341035478    0.5000000000
    0.3332657259    0.7333423839    0.5000000000
    0.3332531337    0.9330497706    0.5000000000
    0.5334073544    0.1328837371    0.5000000000
    0.5336845171    0.3321611778    0.5000000000
    0.5332792938    0.7332808202    0.5000000000
    0.5333689657    0.9332291613    0.5000000000
    0.7334408549    0.1332716585    0.5000000000
    0.7334018640    0.3331440345    0.5000000000
    0.7330025362    0.5333183510    0.5000000000
    0.7339384566    0.7340790608    0.5000000000
    0.7336562320    0.9338414492    0.5000000000
    0.9335185019    0.1335377684    0.5000000000
    0.9331893919    0.3333510680    0.5000000000
    0.9331078330    0.5333413537    0.5000000000
    0.9334554291    0.7334959547    0.5000000000
    0.9335980183    0.9336321242    0.5000000000
    0.0002255003    0.0669001874    0.5000000000
    0.9998779043    0.2667071923    0.5000000000
    0.9997353150    0.4667007726    0.5000000000
    0.9998148315    0.6666859332    0.5000000000
    0.0001439414    0.8668283428    0.5000000000
    0.1999314693    0.0664088372    0.5000000000
    0.2003307971    0.2669824815    0.5000000000
    0.1993948767    0.4668072709    0.5000000000
    0.1996771014    0.6668518839    0.5000000000
    0.1998924785    0.8664974703    0.5000000000
    0.3999259789    0.0661430493    0.5000000000
    0.3996488162    0.2651433273    0.5000000000
    0.4000540395    0.6666681931    0.5000000000
    0.3999643677    0.8665268623    0.5000000000
    0.6000801997    0.0664633036    0.5000000000
    0.6002444160    0.2660915328    0.5000000000
    0.5996955367    0.4658851411    0.5000000000
    0.6012531944    0.6686900755    0.5000000000
    0.6000676074    0.8667433247    0.5000000000
    0.8002164366    0.0668981506    0.5000000000
    0.8000214759    0.2665952806    0.5000000000
    0.7998381971    0.4666324681    0.5000000000
    0.8004072243    0.6670381127    0.5000000000
    0.8003932960    0.8671915465    0.5000000000
    0.4666666667    0.5345545928    0.5000000000
    0.5310782048    0.5340675977    0.5000000000
    0.4022551285    0.4696560595    0.5000000000
acell    1.0    1.0    1.0
rprim
   35.6218507259   20.5556005028    0.0000000000
  -35.6311038635   20.5716274071    0.0000000000
    0.0000000000    0.0000000000   32.1253441186

pp_dirpath   "/home/apps/qsoftw/abinit/PPs/JTH-PBE-atomicdata-1.1/"
pseudos      "ATOMICDATA/B.GGA_PBE-JTH.xml, ATOMICDATA/N.GGA_PBE-JTH.xml, ATOMICDATA/C.GGA_PBE-JTH.xml"

########################################################

Can you tell me if there is something wrong with my input file?

On the other hand I would like to know how to get an invitation code to register in the forum.

**Comment by jmbeuken** [comment]
Hi,

invite code sent...
