### ISSUE TITLE
Yet another 'Abinit Old Version'

### ISSUE THREAD

**Issue by TheQueasle** [abinit/abinit#7]
Hey there,

Is there a location I can download Abinit 8.2.2 (md5sum 5f25250e06fdc0815c224ffd29858860)?

The FTP site (ftp.abinit.org) seems to not be available any longer, and the github tag archive https://github.com/abinit/abinit/archive/8.2.2.tar.gz has a different md5sum than I expected.

Thanks!

**Comment by gmatteo** [comment]
Sorry about that. We are working on it. See https://github.com/spack/spack/pull/6242

**Comment by TheQueasle** [comment]
Thanks!  I’m the one who submitted the PR ;)

**Comment by TheQueasle** [comment]
I think this one can be closed now that the FTP site is functioning once more.

Thanks!
