### ISSUE TITLE
Building with the new LLVM flang

### ISSUE THREAD

**Issue by pawosm-arm** [abinit/abinit#73]
I was trying to build Abinit with the most recent LLVM's new flang. There was actually just one annoying obstacle: the lost modules.

Similarly to gfortran, the new flang supports the `-J` flag, and it needs to be used to make those Fortran modules copied and visible when and as needed. Eventually, I've modified the generated `configure` script with the section below:

```
    llvm)
      abi_fc_vendor_hnt="llvm"
      abi_fc_version_hnt="default"
      abi_sys_spec_hnt="default"
      FCFLAGS_32BITS='-m32'
      FCFLAGS_64BITS='-m64'
      FCFLAGS_PIC='-fPIC -DPIC'
      FCFLAGS_OPENMP='-fopenmp'
      FCFLAGS_OPENMP_OFFLOAD='-fopenmp --offload-arch=__GPU_ARCH__'
      FCFLAGS_MODDIR='-J../mods'
      FCFLAGS_BIGENDIAN='-fconvert=big-endian -frecord-marker=4'
      FCFLAGS_FREEFORM='-ffree-form'
      FCFLAGS_FIXEDFORM='-ffixed-form'
      FCFLAGS_HINTS='-ffixed-line-length=132'
      ;;
```

I assume these things are generated from the contents of the `fc_llvm_default-hints.conf` file, note that the following flags are PGI Fortran specific hence not recognized by the new LLVM flang:

```
big_endian = -mbig-endian -frecord-marker=4 ; replace with -fconvert=big-endian -frecord-marker=4
free = -Mfree                                                            ; replace with -ffree-form
fixed = -Mfixed                                                         ; replace with -ffixed-form
comp = -Mextend -Qunused-arguments            ; replace with -ffixed-line-length=132
```

**Comment by mtorrent** [comment]
Dear `pawosm-arm`,   
Thank you for pointing that out (obsolete config). I’ll include it in the next version.  
Marc
